spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: sasa
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  security:
    user:
      name: gustavo
      password: gustavo
      roles: ADMIN
